name: CI/CD

on: # what conditions trigger the pipeline
  push:
    branches:
      - main
      - demo-failing-test
      - demo-passing
      - demo-lint-fail
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # CI
  ci_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  # CD
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ci_test
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4